#!/bin/bash
set -e

extensionPath="$(dirname "$0")"
arch="$(uname -m)"

if uname -a | grep Msys > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exec "${extensionPath}/dist/gh-repo-explore_windows_amd64/gh-repo-explore" "$@"
  elif [ $arch = "i686" ]; then
    exec "${extensionPath}/dist/gh-repo-explore_windows_386/gh-repo-explore" "$@"
  elif [ $arch = "i386" ]; then
    exec "${extensionPath}/dist/gh-repo-explore_windows_386/gh-repo-explore" "$@"
  fi
elif uname -a | grep Darwin > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exec "${extensionPath}/dist/gh-repo-explore_darwin_amd64/gh-repo-explore" "$@"
  fi
elif uname -a | grep Linux > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exec "${extensionPath}/dist/gh-repo-explore_linux_amd64/gh-repo-explore" "$@"
  elif [ $arch = "i686" ]; then
    exec "${extensionPath}/dist/gh-repo-explore_linux_386/gh-repo-explore" "$@"
  elif [ $arch = "i386" ]; then
    exec "${extensionPath}/dist/gh-repo-explore_linux_386/gh-repo-explore" "$@"
  fi
fi

if [ "$(which go)" = "" ]; then
	echo "go must be installed to use this gh extension on this platform"
	exit 1
fi

exe="cmd.out"

cd "${extensionPath}" > /dev/null
go build -o "${exe}"
cd - > /dev/null

exec "${extensionPath}/${exe}" "$@"
